version: '3.8'

services:
  customer-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/customer-db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - customer-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - customer-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  customer-network:
    driver: bridge

volumes:
  mongodb_data: 